### ISSUE TITLE
Runing idnits on a draft in text format

### ISSUE THREAD

**Issue by dhruvdhody** [ietf-tools/ietf-at-ui#103]
There is no way to run idnits on a text file as we can only input an XML/markdown but sometimes as a reviewer or shepherd, I get a temporary version of the document in text format on which I would still like to run the tool.

This was possible with tools site.

**Comment by kesara** [comment]
I will work on enabling this from the UI.
In the meantime, if you have your draft available under one of the [allowed domains](https://author-tools.ietf.org/about.html#allowed-domains), you can make use of the [idnits API](https://author-tools.ietf.org/doc/#/default/get_api_iddiff).

Example:
https://author-tools.ietf.org/api/idnits?url=https://www.ietf.org/archive/id/draft-segers-tls-cert-validation-ext-00.txt

**Comment by kesara** [comment]
OBE
