### ISSUE TITLE
/abnf Extract - duplication

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/ietf-at-ui#112]
This is more of an FYI than an issue. When I extract ABNF from (e.g.) RFC3986, it all works, but the result is the concatenation of the fragments of ABNF throughout the document plus the complete ABNF from the appendix. The result is therefore full of duplicate lines and invalid.
There's not much you can do about that except document it...

**Comment by kesara** [comment]
I'll add a note on the webpage.
