### ISSUE TITLE
Bug (or serious misfeature) in the bug reporting process

### ISSUE THREAD

**Issue by klensin** [ietf-tools/ietf-at-ui#130]
### Describe the issue

Consider the following scenario
I am trying to report a bug in the xml2rfc processor (Cf. ietf-tools/xml2rfc#887).  To make the problem clear, I should attach either the original RFCXML file, or an excerpt of it. Unfortunately, neither of those is possible  - an XML file is not accepted as an attachment and changing the file extension to ".txt" produces a "something went wrong" message. 

Trying to simply paste a small excerpt of the XML into the body of the issue results in its being processed (by a processor that has different rules than xml2rfc) unless one thinks / knows enough to explicitly mark it as code.

This is bad news and fairly user-hostile.  
I also have no idea what caused this text to go into right-justification (with some supplemental misfeatures) as I was typing but have not been able to figure out how to get it back out of it.  That "feature" does not show up on preview, so I'm attaching (I hope) a screenshot. .:  
![Capture](https://user-images.githubusercontent.com/10297493/188184974-18b30cdc-9a95-46e9-8dd9-b759e06b4221.JPG)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
There are several related places that let you stick arbitrary blob files in a place that will persist (enough), and you can provide links into the issue reports. For this case gist.github.com would be a reasonably good choice.

**Comment by rjsparks** [comment]
Because I saw it happen to someone else recently, I wonder if you managed to get some rtl text in the window briefly? There are browser bugs that cause edit fields to get sticky about normalization when they shouldn't. But this is something that isn't github specific.

**Comment by kesara** [comment]
Closing this issue as this repository is being archived.
Report new issues and feature requests to https://github.com/ietf-tools/ietf-at
