### ISSUE TITLE
RFE: Be able to diff two uploaded files

### ISSUE THREAD

**Issue by moonshiner** [ietf-tools/ietf-at-ui#142]
### Description

I work on suggesting text for documents, and usually i find it clearer to diff an rfcdiff of two sections of text. 
Perhaps the tool could allow that feature. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by moonshiner** [comment]
Sorry, this now seems to appear for me.  What?

This is great, *but* could the "open in web browser" generate a URL that exists for some function of time, so a WG could look at?

**Comment by kesara** [comment]
OBE
