### ISSUE TITLE
Incorrect quoting in iddiff

### ISSUE THREAD

**Issue by mnot** [ietf-tools/ietf-at-ui#146]
### Describe the issue

Quote characters (`"`) in source text seem to be double-escaped in the HTML output - see eg:
  https://author-tools.ietf.org/iddiff?url1=draft-ietf-httpapi-link-template&url2=https://ietf-wg-httpapi.github.io/link-template/draft-ietf-httpapi-link-template.txt  

Section 2.1, the examples. Source .txt document does not quote those characters, and they're simple, straight quotes.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
This is fixed was fixed in iddiff.
