### ISSUE TITLE
idiff should have linkage headers to the complete state of the drafts being compared

### ISSUE THREAD

**Issue by geeohgeegeeoh** [ietf-tools/ietf-at-ui#176]
### Description

the idiff tool is great for reviewing diffs between drafts but it doesn't have linkage/steerage to actually see the entire state of either draft. Nor to any other web asset: its just HTML markup output from the diff program. I think it would benefit from having a minimum of steering/linkage, most specific being the draft(s) in question but the author, nits, history &c pages should be reachable.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
Closing this issue as this repository is being archived.
Report new issues and feature requests to https://github.com/ietf-tools/ietf-at
