### ISSUE TITLE
Not generating PDF

### ISSUE THREAD

**Issue by bobhinden** [ietf-tools/ietf-at-ui#177]
### Describe the issue

When I try to generate a PDF from an XML draft, gives error:  TypeError: Load failed

Works fine for generating html and text version.

See attached.

![Image](https://github.com/ietf-tools/ietf-at-ui/assets/6423658/90b25c48-e364-4648-b622-05da98b9922c)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
Looks like an odd network/browser issue since this works now.
Please re-open the issue if this occurs again.
