### ISSUE TITLE
API documentation misalignment

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/ietf-at-ui#22]
The formatting here is a little off:

![image](https://user-images.githubusercontent.com/67641/136747335-8fe3735b-e47b-4e6e-a46e-c29275d698b4.png)

**Comment by martinthomson** [comment]
Ahh, feel free to pass this on, or close it as you see fit.  I don't think that you should have to deal with shortcomings of the tool.

**Comment by kesara** [comment]
Closing this issue.
We can look into a different OpenAPI documentation tool if there's enough interest.
