### ISSUE TITLE
Misc. suggestions

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/ietf-at-ui#24]
A few suggestions in no particular order:
1. I think the name "IETF @" is confusing. I get that the "@" is "AT" as in "author tools", but I'd really prefer another name that is less clever and more descriptive.
2. The look&feel should be a bit more in line with our other web presences in terms of colors, fonts, etc. Adding an IETF logo might also not be a bad idea.
3. The red box can be closed but just comes back on reload.
4. There should be links to the various tools added that are currently mentioned in the text.
5. When there are errors, they should be shown (and not just "xml2rfc error: text generation error", for example).

**Comment by kesara** [comment]
> I think the name "IETF @" is confusing. I get that the "@" is "AT" as in "author tools", but I'd really prefer another name that is less clever and more descriptive.

I've created #25 to make this change.

> The look&feel should be a bit more in line with our other web presences in terms of colors, fonts, etc. Adding an IETF logo might also not be a bad idea.

I've created #26 for this issue.

> The red box can be closed but just comes back on reload.

This is captured in #27.

**Comment by kesara** [comment]
All the issues have been resolved except for "3".
>The red box can be closed but just comes back on reload.
This will go away when the service is moved to production mode.
Thank you.
