### ISSUE TITLE
large XML file generates a 413 Entity Too Large error when attempting to covert to HTML

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/ietf-at-ui#35]
I tested author-tools.ietf.org with RFC 8881 (rfc8881.xml -> html) and received a 413 error. When I tried to download the file, I received an html file containing the 413 error. 

https://www.rfc-editor.org/info/rfc8881

RFC 8881 is a very long document. Its PDF (which I also couldn't get to generate) is 560 pages long.

**Comment by kesara** [comment]
@ajeanmahoney, Thanks for the bug report.
This issue has been addressed via configuration ranges.
The nginx server now allows file uploads up to ~5MB.
