### ISSUE TITLE
Support two input files for Diff

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/ietf-at-ui#52]
To fully replace rfcdiff, the UI for Diff needs to allow two input files. It's common to use rfcdiff for comparing files that are not just versions n and n-1 of the same I-D.

**Comment by kesara** [comment]
I have been working on this.
https://author-tools.ietf.org/iddiff currently allows comparing two IDs by either uploading a file(s) or providing the draft name(s).

**Comment by becarpenter** [comment]
Looks good, thanks!
