### ISSUE TITLE
API key is invalid

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/ietf-at-ui#59]
The web service is giving me "API key is invalid" for a valid xml file (converting to html). It converts correctly, but very slowly, on the old web service at xml2rfc.tools.ietf.org

**Comment by kesara** [comment]
@becarpenter Thanks for the report.
This is because of a datatracker server issue and the issue on datatracker is fixed now.
Author Tools is working again.

**Comment by kesara** [comment]
Please note there might be some interruptions in the next 10 minutes or so.
Until datatracker issues are rectified.
