### ISSUE TITLE
Diff left/right inversion

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/ietf-at-ui#61]
It drives me a bit crazy that the Diff option on the web UI places the old version at the right and the new version at the left. In all previous history, the old version was at the left, and that just seems more natural.

**Comment by kesara** [comment]
Yeah, old version on the left side makes more sense. I'll fix that.

**Comment by kesara** [comment]
This change has been deployed to [author tools](https://author-tools.ietf.org).
Thanks.
