### ISSUE TITLE
Not clear that naming an RFC works

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/ietf-at-ui#64]
Using the "draft name" option, I was able to enter "RFC9000", with or without a space.  This worked quite well, but it wasn't clear that it would from the labels on the fields.  Consider improving the cues here.

**Comment by kesara** [comment]
Thanks for the bug report.
There are tooltips on https://author-tools.ietf.org/iddiff
Let me know if that can be improved.

**Comment by martinthomson** [comment]
The explanation says " The input files must be a valid Internet-Draft in one of the following formats: ", which is misleading.  And the field is labeled "Draft Name".  Both of these probably need to be changed as well.

**Comment by kesara** [comment]
I'll correct that to include both IDs and RFCs.
