### ISSUE TITLE
URLs are not shareable

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/ietf-at-ui#65]
This tool works great.  It's much faster than rfcdiff and the conversion options are convenient.  However, it doesn't create a resource that can be shared.  This is understandable for cases where files are uploaded, but less so when the inputs are draft names.

**Comment by kesara** [comment]
https://author-tools.ietf.org/iddiff now generates shareable URLs when draft names or URLs are supplied.

Example:
* https://author-tools.ietf.org/diff?url_1=https://www.ietf.org/archive/id/draft-ietf-tsvwg-ecn-l4s-id-20.txt&url_2=https://www.ietf.org/archive/id/draft-ietf-tsvwg-ecn-l4s-id-24.txt
* https://author-tools.ietf.org/diff?id_1=draft-ietf-bess-mvpn-evpn-aggregation-label-01&id_2draft-ietf-bess-mvpn-evpn-aggregation-label-07 (Note: these parameter names will be changed to `doc_1` and `doc_2`. See https://github.com/ietf-tools/ietf-at/issues/66)

Allowed domains (including subdomains) for URL inputs are:
* ietf.org
*  rfc-editor.org
* githubusercontent.com
* github.io
* gitlab.com
