### ISSUE TITLE
iddiff: Need URL file parameter for effective IESG review mails.

### ISSUE THREAD

**Issue by toerless** [ietf-tools/ietf-at-ui#70]
When replying to reviewers of my draft (e.g.: IESG review) i am providing them with a URL showing the diff cause by me replying to their comments/DISCUSS,  e.g.:

http://tools.ietf.org//rfcdiff?url1=https://www.ietf.org/archive/id/draft-ietf-bier-te-arch-10.txt&url2=https://www.ietf.org/archive/id/draft-ietf-bier-te-arch-11.txt

This does not work for https://author-tools.ietf.org/iddiff.

Please also document the appropriate URL format on the web page https://author-tools.ietf.org/iddiff itself, as rfcdiff does as well.

Please note that this needs to support full URL parameters, because it may point to github commits instead of just datatracker urls.

Thanks a lot!

**Comment by kesara** [comment]
Related to https://github.com/ietf-tools/ietf-at/issues/62

**Comment by kesara** [comment]
This feature is now available on https://author-tools.ietf.org/iddiff

Example: https://author-tools.ietf.org/diff?url_1=https://www.ietf.org/archive/id/draft-ietf-tsvwg-ecn-l4s-id-20.txt&url_2=https://www.ietf.org/archive/id/draft-ietf-tsvwg-ecn-l4s-id-24.txt

Allowed domains (including subdomains) for URL inputs are:
* ietf.org
* rfc-editor.org
* githubusercontent.com
* github.io
* gitlab.com
