### ISSUE TITLE
Diff with latest - save output

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/ietf-at-ui#73]
When collaborating with co-authors, I often send them a diff file during document development. Could "Diff with latest" offer the ability to save the result (as is possible with iddiff)?

**Comment by kesara** [comment]
Yes, It's possible to add this feature.
There's also a different view for draft comparisons that act similar to rfcdiff: https://author-tools.ietf.org/iddiff

**Comment by tony1athome** [comment]
+1
I was unable to save a copy of iddiff output either.  This is a truly vital capability. I will be using the legacy rfcdiff page until there's something comparable.

**Comment by kesara** [comment]
@tony1athome, You can use the https://author-tools.ietf.org/iddiff and save the output from there. And also it's possible to get a sharable URL from that page.
Example: https://author-tools.ietf.org/diff?doc_1=draft-ietf-privacypass-auth-scheme-05

**Comment by QiufangMa** [comment]
I had the same issue,  https://author-tools.ietf.org/iddiff cannot save the output, and a sharable URL is only possible when I've uploaded the lastest version of the draft to datatrack, right? Sometimes we do want to send the co-authors the under-developed draft which has not been submited yet.

**Comment by becarpenter** [comment]
Hi Qiufang,

You can save from your browser (on Firefox it's File/Save Page As...). I think that is exactly the same as for the old rfcdiff program.

Regards
    Brian Carpenter

**Comment by kesara** [comment]
@QiufangMa Can you provide me with your Web Browser and Operating System? Also, any error messages that you get.

>sharable URL is only possible when I've uploaded the lastest version of the draft to datatrack, right?

That's partially correct.
If you are using a GitHub / GitLab repository, you can compare drafts with a sharable link without submitting changes to datatracker.
Example:
https://author-tools.ietf.org/diff?url_1=https://github.com/IETF-OPSAWG-WG/lxnm/raw/master/I-D-sap/draft-ietf-opsawg-sap.txt

**Comment by QiufangMa** [comment]
@becarpenter @kesara Thanks for the quick reply. I am using Google Chrome 103.0.5060.134 (Win10 OS), the Save Page As icon is just disabled, and nothing happens if I use Ctrl+S. I 'll have a try with Firefox latter.

**Comment by kesara** [comment]
@QiufangMa I can confirm that Google Chrome (104.0.5112.79  on MacOS) have disabled **Save Page As** for blobs. :(

**Comment by kesara** [comment]
There was a report that *Microsoft Edge* has the same issue.

**Comment by becarpenter** [comment]
So why use blob: at all?

**Comment by kesara** [comment]
> So why use blob: at all?

Because the Author Tools API endpoint can generate JSON and HTML output.
`iddiff` output is HTML, but if there were any errors, API will reply with JSON.
Treating the output as blob makes it easy to handle these cases.
This project ietf-at-ui is just an HTML site that talks to the Author Tools API.

**Comment by kesara** [comment]
I have updated the [iddiff](https://author-tools.ietf.org/iddiff) UI to include a download button and other buttons.

This should fix the issue on Chrome, Edge etc.

**Comment by tony1athome** [comment]
Thank you!  That works well!

Tony
