### ISSUE TITLE
iddiff - filename

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/ietf-at-ui#75]
When I save the results of iddiff, it is automatically named index.htm. That is unhelpful and might even be problematic if saved into a general folder. Could we have a constructed name as with old rfcdiff?

**Comment by kesara** [comment]
@becarpenter are you referring to the output from [Diff with latest](https://author-tools.ietf.org/) or [iddiff output](https://author-tools.ietf.org/iddiff)?

**Comment by becarpenter** [comment]
iddiff for sure.

**Comment by kesara** [comment]
Thanks. _I was testing with labels and URL inputs._

This happens only on iddiff outputs with a file upload.

**Comment by kesara** [comment]
I have updated the [iddiff](https://author-tools.ietf.org/iddiff) UI to provide a download filename with #123.

**Comment by becarpenter** [comment]
Thanks, perfect.
