### ISSUE TITLE
Feature request for iddiff: choice of format

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/ietf-at-ui#84]
_rfcdiff_ allows the user a number of choices of output format. Can we have the same for _iddiff_ please? (As far as I can see, the RFC Editor uses the _Html wdiff_ option routinely, and for some applications it's much better than side-by-side.)

For what it's worth, this is the only reason I still use _rfcdiff_ (see the previous issue #83).

**Comment by kesara** [comment]
`wdiff` option is on the pipeline for things to come. (https://github.com/ietf-tools/iddiff/issues/5)

**Comment by kesara** [comment]
**wdiff** option is now available on https://author-tools.ietf.org/iddiff/
