### ISSUE TITLE
missing display of warnings

### ISSUE THREAD

**Issue by alicerusso** [ietf-tools/ietf-at-ui#92]
Would be nice if the warnings are displayed, perhaps optionally.
For example, with input file https://www.ietf.org/archive/id/draft-ietf-httpbis-http2bis-07.xml
click "HTML", there are zero warnings.

However, on the command line, the warnings are:
> Warning: rfc2629-xhtml.ent is no longer needed as the special processing of non-ASCII characters has been superseded by direct support for non-ASCII characters in RFCXML.
> Warning: rfc2629-xhtml.ent is no longer needed as the special processing of non-ASCII characters has been superseded by direct support for non-ASCII characters in RFCXML.
> Warning:rfc2629-xhtml.ent is no longer needed as the special processing of non-ASCII characters has been superseded by direct support for non-ASCII characters in RFCXML.
> Warning: rfc2629-xhtml.ent is no longer needed as the special processing of non-ASCII characters has been superseded by direct support for non-ASCII characters in RFCXML.
> draft-ietf-httpbis-http2bis-07.xml(16): Warning: Setting consensus="true" for IETF STD document (this is not the schema default, but is the only value permitted for this type of document)
> draft-ietf-httpbis-http2bis-07.xml(687): Warning: Found SVG with width or height specified, which will make the artwork not scale.  Specify a viewBox only to let the artwork scale.
>  Created file draft-ietf-httpbis-http2bis-07.html

**Comment by alicerusso** [comment]
So, clicking "Validate (idnits)" does display some xml2rfc warnings (in addition to idnits output). However, with the file above as input, this warning does not appear (presumably bc it's specific to HTML and PDF renderings):

> Warning: Found SVG with width or height specified, which will make the artwork not scale. Specify a viewBox only to let the artwork scale.

Only this one appears under "Warnings":
> Setting consensus="true" for IETF STD document (this is not the schema default, but is the only value permitted for this type of document)

**Comment by kesara** [comment]
This has been fixed now with https://github.com/ietf-tools/ietf-at/pull/222
